# Generated by Django 4.1.3 on 2022-12-15 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modalidade', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_ativos', models.IntegerField()),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='byebnk.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_ativos', models.IntegerField()),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='byebnk.ativo')),
            ],
            options={
                'verbose_name_plural': 'aplicações',
            },
        ),
    ]
