# Generated by Django 4.1.3 on 2022-12-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byebnk', '0002_alter_ativos_nome_resgate_aplicacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ativos',
            new_name='Ativo',
        ),
        migrations.AlterModelOptions(
            name='aplicacao',
            options={'verbose_name_plural': 'aplicações'},
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='resgate',
            name='usuario',
        ),
    ]
