# Generated by Django 4.1.3 on 2022-12-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('byebnk', '0003_rename_ativos_ativo_alter_aplicacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='byebnk.ativo'),
        ),
        migrations.AlterField(
            model_name='resgate',
            name='ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='byebnk.ativo'),
        ),
    ]
